[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = { mode = "https://mainnet.mode.network"}
fs_permissions = [{ access = "read", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
